---
topic: "land"
title: "Trends in Silviculture in B.C. (1987-2023): Methods"
output: 
  pdf_document:
    latex_engine: xelatex
    pandoc_args: 
      - --variable
      - colorlinks=true
      - --variable
      - linkcolor=blue
      - --variable
      - urlcolor=blue
      - --variable
      - citecolor=blue
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
require(knitr)
library(readr) #read CSV file
library(dplyr) #data cleaning
library(tidyr) #wide to long df format
library(ggplot2) #plotting
library(envreportutils) #for soe_theme(), package from GitHub
library(here)

opts_chunk$set(echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.height=5)
```

# METHODS

The [**R** code](http://www.r-project.org) for creating the graphs
presented on this page is available on
[GitHub](https://github.com/bcgov/forest-management-indicators).

## Source Data

The Silviculture analysis uses data from:

1.  [Reporting Silviculture Updates and Land Status Tracking System
    (RESULTS)](https://www2.gov.bc.ca/gov/content?id=F62992DA5B324446AD5E1B5BFFA404CC%3E)
    and

2.  [Seed Planning and Registry System
    (SPAR)](https://www2.gov.bc.ca/gov/content?id=A2F6834E799241929E4113210A9BDD08)

Wherever possible, the analysis used public data layers from the B.C.
Geographic Warehouse[^1] released under either the Open Government
Licence---British Columbia or the B.C. Crown Copyright Licence:

[^1]: Detailed descriptions and downloads of the source layers are
    available from the B.C. Data Catalogue at:
    <http://catalogue.data.gov.bc.ca/dataset>

-   **Opening_VW**:
    [WHSE_FOREST_VEGATATION_OPENING_VW](https://catalogue.data.gov.bc.ca/dataset/f6d17c00-d4b9-401b-a20e-ef7e37b6d5e3)
    (Licence: [Open Government Licence - British
    Columbia](http://www2.gov.bc.ca/gov/content?id=A519A56BC2BF44E4A008B33FCF527F61))

-   **Seedlot**:
    [WHSE_FOREST_VEGATATION_SEED_SEEDLOT](https://catalogue.data.gov.bc.ca/dataset/686e10d6-78e3-4779-9a8b-08015a5c070d)
    (Licence: [Open Government Licence - British
    Columbia](http://www2.gov.bc.ca/gov/content?id=A519A56BC2BF44E4A008B33FCF527F61))

-   **Veglot**:
    [WHSE_FOREST_VEGETATION.SEED_VEG_LOT](https://catalogue.data.gov.bc.ca/dataset/2456f4ed-7e47-438f-9ab5-711268c92075)
    (Licence: [Open Government Licence - British
    Columbia](http://www2.gov.bc.ca/gov/content?id=A519A56BC2BF44E4A008B33FCF527F61))

-   **Activity Treatment Unit**:
    [WHSE_FOREST_VEGATATION_RSLT_ACTIVITY_TREATMENT_UNIT](https://catalogue.data.gov.bc.ca/dataset/07cabbdf-d7bf-4c50-919d-5b7d80086ef5)
    (Licence: [Open Government Licence - British
    Columbia](http://www2.gov.bc.ca/gov/content?id=A519A56BC2BF44E4A008B33FCF527F61))

-   **Planting**: WHSE_FOREST_VEGATATION_RSLT_PLANTING_RSLT (Licence:
    [Access
    Only](https://www2.gov.bc.ca/gov/content?id=1AAACC9C65754E4D89A118B875E0FBDA))

-   **Seedlot Genetic Worth**: SEEDLOT_GENETIC_WORTH (Licence: [Access
    Only](https://www2.gov.bc.ca/gov/content?id=1AAACC9C65754E4D89A118B875E0FBDA))

-   **Org Unit**: Appendix I – Lookup Tables

-   **CoastInteriorOrgUnit**: Appendix I – Lookup Tables

-   **SILV_FUND_SRC_CODE**: Appendix I – Lookup Tables

## Fiscal Year

Fiscal year will be display as follows:

-   Formula used: Fiscal Yr:
    $If(Month([DATE])<4,Year([DATE])-1,Year([DATE]))$

-   Example: 1987-04-01 and 1988-03-31 Fiscal Year = 1988

## Baseline Make Table Queries

All queries are built in Microsoft Access 2007. Make Table queries are
used to create baseline data tables for increased efficiency and data
auditability. Note that all data reported after April 1, 1970 is added
to the baseline but the data are subset to more recent years in the
final queries.

## Silvicultural Systems

*1a-Make Opening (outcome: 1a-Opening)*

Extracts all the required attributes from the Opening_VW to create the
1a-Opening table to get a unique list of all openings.

*2a-Make Raw Silv System (outcome: 2a-Raw Silv System)*

Lists all completed disturbance reporting from the Activity Treatment
Unit table.

| **Field**      | **Criteria** | **Details**                |
|----------------|--------------|----------------------------|
| SILV_BASE_CODE | DN           | Disturbance Reporting Only |
| RESULTS_IND    | Y            | Completed activities only  |

*2a-Detailed Silv System and Fiscal Date*

Joins the 2a-Raw Silv System with the 1a-Make Opening and creates some
new calculated attributes.

| **Field** | **Criteria** | **Details** |
|:-------------|:---------------------------------|:-----------------------|
| NewSilv | `IIf([DISTURBANCE_CODE] In ("L","S") And [SILV_SYSTEM_CODE] Is Null, "CLEAR", [SILV_SYSTEM_CODE])` | Identifies disturbance records as Logging or Salvage and identifies them as a clearcut |
| Dist Start Yr | `IIf(Month([ATU_START_DATE])<4, Year([ATU_START_DATE])-1, Year([ATU_START_DATE]))` | Changes the disturbance start date to calendar end |
| Dist End Yr | `IIf(Month([ATU_COMPLETION_DATE])<4, Year([ATU_COMPLETION_DATE])-1, Year([ATU_COMPLETION_DATE]))` | Changes the disturbance end date to calendar end |
| Disturbance Type | `IIf([DISTURBANCE_CODE] In ("L","S") And [2a-Raw Silv System]![SILV_SYSTEM_CODE] Is Null Or [2a-Raw Silv System]![SILV_SYSTEM_CODE] Is Not Null, "Harvest", "Not Harvest")` | Identifies disturbance records as Harvest or Not Harvest |

*2b-ATU DN Detail Best Date*

Joins the 2a-Detailed Silv System and Fiscal Date NewSilv with the
following Silv System Code lookup table and defines the best fiscal year
to report the treatments to.

| **SILV_SYSTEM_CODE** | **Silviculture System**    |
|:---------------------|:---------------------------|
| CCRES                | Clearcutting with reserves |
| CLEAR                | Clearcutting               |
| COPPI                | Partial cutting            |
| IMCUT                | Partial cutting            |
| PATCT                | Partial cutting            |
| RETEN                | Clearcutting with reserves |
| SEEDT                | Partial cutting            |
| SELEC                | Partial cutting            |
| SHELT                | Partial cutting            |

| **Field** | **Criteria** | **Details** |
|:----------------|:-----------------------|:-----------------------------|
| Best Dist End Yr | `IIf([Dist End Yr] Is Null,[Dist Start Yr],[Dist End Yr])` | Populates missing disturbance ends years with the disturbance start year |

*2c-Harvest Sum of DN Area*

Summarizes 2b-ATU DN Detail Best Date to calculate the disturbance area
in an opening.

| **Field**              | **Criteria**             | **Details**    |
|:-----------------------|:-------------------------|:---------------|
| Disturbance Type       | `= "Harvest"`            | Group by (Row) |
| OPENING_ID             |                          | Group by (Row) |
| LastOfBest Dist End Yr | `LAST(Best Dist End Yr)` | Group by (Row) |
| OPENING_GROSS_AREA     |                          | Group by (Row) |
| DN_Area                | `TREATMENT_AMOUNT`       | Sum            |

*2d-Harvest Best Area*

Calculates the best harvest area using 2c-Harvest Sum of DN Area.

| **Field** | **Criteria** | **Details** |
|:---------------|:-----------------------|:-------------------------------|
| DN Area | \<0 |  |
| Best Harv Area | `IIf([DN Area]<=[OPENING_GROSS_AREA], [DN Area],[OPENING_GROSS_AREA])` | Where the sum of the DN Area is greater than the opening gross area, the opening gross area is used as the disturbance area |

*2e-Harvest Silv System Area*

Summarizes 2b-ATU DN Detail Best Date to calculate the disturbance area
in an opening.

| **Field**              | **Criteria**  | **Details**       |
|:-----------------------|:--------------|:------------------|
| Disturbance Type       | `= "Harvest"` | Group by (Row)    |
| OPENING_ID             |               | Group by (Row)    |
| LastOfBest Dist End Yr |               | Group by (Row)    |
| SOF Silv System        |               | Group by (Column) |
| TREATMENT_AMOUNT       | `Sum`         | Sum               |

*2f-Make Silv System Ratio*

Joins the 2e-Harvest Silv System Area with the 2d-Harvest Best Area and
creates some new calculated attributes.

| **Field**   | **Criteria**                     | **Details** |
|:------------|:---------------------------------|:------------|
| CCRES_pct   | `Round(([CCRES]/[DN Area]),2)`   |             |
| CLEAR_pct   | `Round(([CLEAR]/[DN Area]),2)`   |             |
| PARTIAL_pct | `Round(([PARTIAL]/[DN Area]),2)` |             |

*2g-Harvest Silv System Best Area*

Joins the 2f-Make Silv System Ratio with the 2d-Harvest Best Area and
creates some new calculated attributes.

| **Field**     | **Criteria**                     |
|:--------------|:---------------------------------|
| Final CCRES   | `[CCRES_pct]*[Best Harv Area]`   |
| Final CLEAR   | `[CLEAR_pct]*[Best Harv Area]` |
| Final PARTIAL | `[PARTIAL_pct]*[Best Harv Area]` |

*2h-Final Silv System*

Summarizes 2g-Harvest Silv System Best Area to calculate the disturbance
area in an opening by silvicultural system.

| **Field**              | **Criteria** | **Details**    |
|:-----------------------|:-------------|:---------------|
| LastOfBest Harv End Yr | `>= 1987`    | Group by (Row) |
| Final CCRES            |              | Sum            |
| Final CLEAR            |              | Sum            |
| Final PARTIAL          |              | Sum            |

## Disturbances and Reforestation

*2i-Disturbance Sum of DN Area*

Summarizes 2b-ATU DN Detail Best Date to calculate the natural
disturbance area in an opening.

| **Field**              | **Criteria**             | **Details**    |
|:-----------------------|:-------------------------|:---------------|
| Disturbance Type       | `"Not Harvest"`          | Group by (Row) |
| OPENING_ID             |                          | Group by (Row) |
| LastOfBest Dist End Yr | `LAST(Best Dist End Yr)` | Group by (Row) |
| OPENING_GROSS_AREA     |                          | Group by (Row) |
| DN Area                | `TREATMENT_AMOUNT`       | Sum            |

*2j-Disturbance Best Area*

Calculates the best harvest date and area using the 1a-Opening and
2e-Summary DN Area.

| **Field** | **Criteria** | **Details** |
|:---------------|:-------------------|:-----------------------------------|
| Best Disturb Area | `IIf([DN Area]<= [OPENING_GROSS_AREA], [DN Area], [OPENING_GROSS_AREA])` | Where the sum of the DN Area is less than the opening gross area, the DN Area is used as the Best Disturb area, else the opening gross area is used |

*2k-Final Disturbance by Year*

Summarises 2j-Disturbance Best Area by Year.

| **Field**              | **Criteria**    | **Details**    |
|:-----------------------|:----------------|:---------------|
| LastOfBest Dist End Yr | `Where >= 1987` | Group by (Row) |
| Best Disturb Area      |                 | Sum            |

*2l-All Denudation*

Joins the 2h-Final Silv System with the 2k-Final Disturbance by Year to
sum the total harvested and total natural disturbance areas by fiscal
year.

| **Field** | **Criteria** | **Details** |
|:-------------|:------------------------------------------|:-------------|
| Total Harvested | `[Final CCRES]+[Final CLEAR]+[Final PARTIAL]` |  |
| Total Disturbance | `[Final CCRES]+[Final CLEAR]+[Final PARTIAL]+[Not Harvest Area]` |  |

The reforestation number is calculated in the Trends in Genetic Resource
Conservation and Management of B.C. Forests indicator analysis. Details
on how the reforestation number was calculated are available in the
indicators methods document (query - 3g-Assess Regen Type – Set
Threshold).

## Silviculture Treatments

*6a-Make Fertilization (outcome: 6a-Fertilization)*

Joins the Activity Treatment Unit and Opening_VW tables using the
Opening_ID, joins the Activity Treatment Unit to the Org Unit using the
ORG_UNIT_NO and joins the Org Unit to the CoastInteriorOrgUnit using the
ORG_UNIT_CODE to get a complete list of fertilization activities.

| **Field**           | **Criteria**    | **Details** |
|:--------------------|:----------------|:------------|
| SILV_BASE_CODE      | `FE`            |             |
| SILV_TECHNIQUE_CODE | `Is Null or CA` |             |
| TREATMENT_AREA      | `> 0`           |             |

*6b-Fertilization with Coast Interior*

Joins 6a-Fertilization with 1a-Opening using the Opening_ID, joins
6a-Fertilization with SILV_FUND_SRCE_CODE using the SILV_FUND_SRCE_CODE,
and joins the 1a-Opening with the Org Unit using the ORG_UNIT_NO. These
tables are joined to summarize fertilization volume gains for the coast
and interior (two different calculations) by fiscal year.

| **Field** | **Criteria** | **Details** |
|:----------------|:-------------------------------------|:----------------|
| Fert Yr | `$IIf(Month([ATU_COMPLETION_DATE]), 4,Year([ATU_COMPLETION_DATE])-1, Year([ATU_COMPLETION_DATE]))$` |  |
| Fertilization Volume Gain | `$IIf([Coast_interior]="I", [TREATMENT_AMOUNT]*0.15*65, [TREATMENT_AMOUNT]*0.3*65)$` | Interior = 0.15m^3^/ha/yr Coast = 0.3m^3^/ha/yr |

*6c-Fertilization with Volume Gains – BC*

Summarizes 6b-Fertilization with Coast Interior Fertilization Area and
Fertilization Volume Gain by Fiscal Year.

| **Field**                 | **Criteria**       | **Details**    |
|:--------------------------|:-------------------|:---------------|
| Fert Yr                   | `Between >= 1970`  | Group by (Row) |
| Fertilization Area        | `TREATMENT_AMOUNT` | Sum            |
| Fertilization Volume Gain |                    | Sum            |
| Category                  | `<> Legal`         | Where          |

*7a-Make Spacing (outcome: 7a-Spacing)*

Joins the Activity Treatment Unit and Opening_VW tables using the
Opening_ID to summarize spacing activities.

| **Field**        | **Criteria** | **Details**                 |
|:-----------------|:-------------|:----------------------------|
| SILV_BASE_CODE   | `JS`         |                             |
| SILV_METHOD_CODE | `< > LAYOT`  | Ignore preparatory activity |
| TREATMENT_AREA   | `> 0`        |                             |

*7b-Spacing Volume Gains*

Joins 7a-Spacing with 1a-Opening using the Opening_ID, joins 7a-Spacing
with SILV_FUND_SRCE_CODE using the SILV_FUND_SRCE_CODE, and joins the
1a-Opening with the Org Unit using the ORG_UNIT_NO. These tables are
joined to summarize spacing volume by fiscal year.

| **Field** | **Criteria** | **Details** |
|:--------------|:---------------------------------------|:----------------|
| Incremental |  |  |
| JS Gains | `(0.25*[TREATMENT_AMOUNT])*65` | Gains = .25m^3^/ha/yr |
| JS Yr | `JS Yr: IIf(Month([ATU_COMPLETION_DATE])<4, Year([ATU_COMPLETION_DATE])-1, Year([ATU_COMPLETION_DATE]))` |  |
| Category | `Not in (Legal, Other)` | Excludes any legally obligated spacing activities |

*7c-Spacing with Volume Gains – BC*

Summarizes 7b-Spacing with Volume Gains Spacing Area and Incremental JS
Gains by JS Year.

| **Field**            | **Criteria**       | **Details**    |
|:---------------------|:-------------------|:---------------|
| JS Yr                | `>= 1970`          | Group by (Row) |
| Spacing Area         | `TREATMENT_AMOUNT` | Sum            |
| Incremental JS Gains |                    | Sum            |
| Category             | `<> Legal`         | Where          |

*8a-Make Pruning (outcome: 8a-Pruning)*

Joins the Activity Treatment Unit and Opening_VW tables using the
Opening_ID to summarize pruning activities.

| **Field**        | **Criteria** | **Details**                  |
|:-----------------|:-------------|:-----------------------------|
| SILV_BASE_CODE   | `PR`         |                              |
| SILV_METHOD_CODE | `<> LAYOT`   | Removes preparatory activity |
| TREATMENT_AREA   | `> 0`        |                              |

*8b-Pruning Area*

Joins 8a-Pruning with 1a-Opening using the Opening_ID, joins 8a-Pruning
with SILV_FUND_SRCE_CODE using the SILV_FUND_SRCE_CODE, and joins the
1a-Opening with the Org Unit using the ORG_UNIT_NO. These tables are
joined to summarize pruning volume by fiscal year.

| **Field** | **Criteria** | **Details** |
|:----------|:------------------------------------------------|:----------|
| PR Yr | `PR Yr: IIf(Month([ATU_COMPLETION_DATE])<4, Year([ATU_COMPLETION_DATE])-1, Year([ATU_COMPLETION_DATE\]))` |  |

*8d-Pruning – BC*

Summarizes 8b-Pruning Area Pruning Area by PR Year.

| **Field**    | **Criteria**       | **Details**    |
|:-------------|:-------------------|:---------------|
| PR Yr Yr     | `>= 1970`          | Group by (Row) |
| Pruning Area | `TREATMENT_AMOUNT` | Sum            |
| Category     | `<> Legal`         | Where          |

*1a-Make Opening (outcome: 1a-Opening)*

Extracts the all the required attributes from the Opening_VW to create
the 1a-Opening table to get a unique list of all openings.

*1b-Make Planting Activities (outcome: 1b-Planting Activities)*

Joins the Activity Treatment Unit and Opening_VW tables using the
Opening_ID to summarize planting activities.

| **Field**      | **Criteria** | **Details**                |
|:---------------|:-------------|:---------------------------|
| SILV_BASE_CODE | `PL`         |                            |
| ACT_PLANTED_NO | `> 0`        | Must contain planted trees |

*1c-Make Planted Trees (outcome: 1b-Planted Trees)*

Joins the Activity Treatment Unit and Opening_VW tables using the
Opening_ID and joins the Activity Treatment Unit and Planting RSLT using
the ACTIVITY_TREATMENT_UNIT_ID to summarize planted trees.

| **Field**      | **Criteria** | **Details**                |
|:---------------|:-------------|:---------------------------|
| SILV_BASE_CODE | `PL`         |                            |
| ACT_PLANTED_NO | `> 0`        | Must contain planted trees |

*5a-Backlog Planting*

Joins the 1a-Opening to the 1b-Planted Activities using the Opening_ID
and joins the 1b-Planted Activities to the SILV_FUND_SRCE_CODE using the
SILV_FUND_SRCE_CODE to summarize planting activities.

| **Field** | **Criteria** | **Details** |
|:---------------|:-------------------------------------|:-----------------|
| Category | `FFT or FCI` | FFT and FCI is used to identify the post-2005 backlog planting |
| Backlog Planted Yr | `IIf(Month([ATU_COMPLETION_DATE])<4, Year([ATU_COMPLETION_DATE])-1, Year([ATU_COMPLETION_DATE]))` |  |
| Backlog PL Volume Gain | `(2.93*[TREATMENT_AMOUNT])*65` | Gains = 2.93 m^3^/ha/yr |

*5b- Backlog Planting with Volume Gains*

Summarizes 8b-Pruning Area Pruning Area by PR Year.

| **Field**              | **Criteria**            | **Details**    |
|:-----------------------|:------------------------|:---------------|
| Backlog Planted Yr     | `>= 1970`               | Group by (Row) |
| Backlog Planting Area  | `TREATMENT_AMOUNT`      | Sum            |
| Backlog PL Volume Gain |                         | Sum            |
| Category               | `Not In (Legal, Other)` | Where          |

*3a-Planting Details with Seedlot*

Joins the 1a-Opening to the 1b-Planted Activities using the opening_ID,
joins the 1b-Planted Activities to the 1c-Planted Trees using the
ACTIIVTY_TREATMENT_UNIT_ID and joins the 1c-Planted Trees to the Seedlot
using the SEEDLOT_NUMBER to summarize planted tree details needed to
calculate genetic gains.

| **Field** | **Criteria** | **Details** |
|:------------|:---------------------------------------------|:------------|
| Disturb Start Yr | `$IIf(Month([DISTURBANCE_START_DATE]<4, Year([DISTURBANCE_START_DATE])-1, Year([DISTUBANCE_START_DATE]))`\$ | Converts the Disturbance Start Date to Fiscal year |
| Disturb End Yr | `IIf(Month([DISTURBANCE_END_DATE]<4, Year([DISTURBANCE_END_DATE])-1, Year([DISTURBANCE_END_DATE]))` | Converts the Disturbance End Date to Fiscal year |
| Planted Yr | `IIf(Month([ATU_COMPLETION_DATE])<4, Year([ATU_COMPLETION_DATE])-1, Year([ATU_COMPLETION_DATE]))` | Converts the Planting Date to Fiscal year |
| SeedClass | `IIf([GENETIC_CLASS_CODE]="B" And [SUPERIOR_PRVNC_IND]="Y","B+", IIf([GENETIC_CLASS_CODE]="B" And [SUPERIOR_PRVNC_IND]="N","B", IIf([GENETIC_CLASS_CODE]="B" And [SUPERIOR_PRVNC_IND] Is Null,"B", IIf([GENETIC_CLASS_CODE]="A","A", IIf([GENETIC_CLASS_CODE] Is Null,"B")))))` | Assign Seed Class |
| ProratePLArea | `Round((([1c-Planted Trees]![NUMBER_PLANTED]/ [1c-Planted Trees]![ACT_PLANTED_NO])* [1c-Planted Trees]![TREATMENT_AMOUNT]),2)` | Prorated species planted by planted area |

*4a-Calculate Genetic Worth G Gains by Opening*

Summarizes 3a-Planting Details with Seedlot by Opening_ID where the
GENETIC_WORTH_CODE = "GVO" or the SeedClass = "A" OR "B+".

| **Field** | **Criteria** | **Details** |
|:---------------|:---------------|:-------------------------------------|
| GENETIC_WORTH_CODE | `GVO` | Volume Gain |
| SeedClass | `In (A, B+)` | "A"=Orchard and "B+"=Planted Natural Stand Superior |

*4b-Calculate Genetic Worth G Gains by Opening*

Calculates the Productivity Gain for each opening in the 4a-Calculate
Genetic Worth GVO Gains by Opening table.

| **Field** | **Criteria** | **Details** |
|:--------------|:------------------------------------------|:--------------|
| Productivity Gain | `GProductivity Gain: IIf([PlantedYr]<=2009, 0.41[ProratePLArea]*65, IIf([PlantedYr]=2010, 0.53[ProratePLArea]65, IIf([PlantedYr]>2010, 0.615[ProratePLArea]*65)))` | \< = 2009: 0.41m^3^/ha/yr 2010: 0.53m^3^/ha/yr \>2010: 0.615m^3^/ha/yr |

*4c-Summary Genetic Gains from Planting BC*

Takes 4b-Calculate Genetic Productivity G Gains by Opening and
summarizes gains by area and volume.

| **Field**          | **Criteria**          | **Details**    |
|:-------------------|:----------------------|:---------------|
| Planted Yr         | `>= 1970`             | Group by (Row) |
| Select Seed Area   | `(ProratePLArea)`     | Sum            |
| Select Seed Volume | `(Productivity Gain)` | Sum            |

*9a-Silvicuture Treatments BC Area*

Joins the following tables to report all of the silviculture treatment
area summaries in one table:

-   5b-Backlog Planting with Volume Gains BC;

-   4c-Summary Genetic Gains from Planting BC;

-   6c-Fertilization with Volume Gains – BC;

-   7c-Spacing with Volume Gains – BC; and

-   8d-Pruning – BC.

*9b-Silvicuture Treatments BC Area*

Joins the following tables to report all of the silviculture treatment
area summaries in one table:

-   5b-Backlog Planting with Volume Gains BC;

-   4c-Summary Genetic Gains from Planting BC;

-   6c-Fertilization with Volume Gains – BC;

-   7c-Spacing with Volume Gains – BC; and

-   8d-Pruning – BC.

## Appendix I – Lookup tables

### Org Unit

| **ORG_UNIT_NO** | **ORG_UNIT_CODE** | **ROLLUP_REGION_CODE** |
|:----------------|:------------------|:-----------------------|
| 1826            | DCC               | RCB                    |
| 15              | DCK               | RSC                    |
| 43              | DCR               | RWC                    |
| 1828            | DCS               | RTO                    |
| 42              | DDC               | RNO                    |
| 46              | DFN               | RNO                    |
| 1827            | DHW               | RSI                    |
| 34              | DJA               | ROM                    |
| 21              | DKA               | RTO                    |
| 32              | DKM               | RSK                    |
| 56              | DMH               | RCB                    |
| 38              | DMK               | ROM                    |
| 1823            | DND               | RSK                    |
| 1832            | DNI               | RWC                    |
| 1829            | DOS               | RTO                    |
| 1825            | DPC               | RNO                    |
| 18              | DPG               | ROM                    |
| 48              | DQC               | RWC                    |
| 50              | DQU               | RCB                    |
| 1831            | DRM               | RKB                    |
| 27              | DSC               | RSC                    |
| 1902            | DSE               | RKB                    |
| 1619            | DSI               | RWC                    |
| 23              | DSQ               | RSC                    |
| 1824            | DSS               | RSK                    |
| 30              | DVA               | ROM                    |

### CoastInteriorOrgUnit

| **ROLLUP_REGION_CODE** | **ORG_UNIT_CODE** | **ORG_UNIT_NAME** | **Coast_Interior** |
|:---|:---|:---|:---|
| RCB | DCC | Cariboo-Chilcotin | I |
| RCB | DMH | 100 Mile House | I |
| RCB | DQU | Quesnel | I |
| RKB | DRM | Rocky Mountain | I |
| RKB | DSE | Selkirk | I |
| RNO | DFN | Fort Nelson | I |
| RNO | DPC | Peace | I |
| ROM | DJA | Fort St. James | I |
| ROM | DMK | Mackenzie | I |
| ROM | DPG | Prince George | I |
| ROM | DVA | Vanderhoof | I |
| RSC | DCK | Chilliwack | C |
| RSC | DSC | Sunshine Coast | C |
| RSC | DSQ | Sea to Sky | C |
| RSK | DKM | Coast Mountains | I |
| RSK | DND | Nadina | I |
| RSK | DSS | Skeena Stikine | I |
| RTO | DCS | Cascades | I |
| RTO | DKA | Thompson Rivers | I |
| RTO | DOS | Okanagan Shuswap | I |
| RWC | DCR | Campbell River | C |
| RWC | DNI | North Island - Central Coast | C |
| RWC | DQC | Haida Gwaii | C |
| RWC | DSI | South Island | C |

### SILV_FUND_SRC_CODE

| **SILV_FUND_SRCE_CODE** | **DESCRIPTION** | **Category** |
|:---|:---|:---|
| BCT | BC Timber Sales | Legal |
| CBI | Carbon Offset Investment | Other |
| CL | Catastrophic Losses | Operational |
| ERP | Ecosystem Restoration Program | Other |
| FCE | FCI under FESBC funding | FCI |
| FCM | FCI under Ministry funding | FCI |
| FES | Forest Enhancement Society BC | FES |
| FID | Forest Investment Account - FRPA 108 | FIA |
| FIL | Forest Investment Account - licensee | FIA |
| FIM | Forest Investment Account - ministry | FIA |
| FIV | Forest Investment Vote | FIA |
| FMC | COMFOR | Other |
| FME | Forest Worker Development Program | Other |
| FMY | Youth Fund | Other |
| FR | FRDA I & II | FRDA |
| FRP | FRPA - Application For Relief | Legal |
| FTL | Forests for Tomorrow Lic Admin | FFT |
| FTM | Forests for Tomorrow MOF Admin | FFT |
| GA | Other Agencies or Voluntary Work | Other |
| GAC | Corrections | Other |
| GFS | Forest Stand Management Fund | Legal |
| GJF | Job Creation, Federal | Other |
| GJJ | Job Creation, Joint | Other |
| GJM | Job Creation, MOF | Other |
| IA | Industrial Appraisal | Legal |
| IIR | Industrial Incr., Required | Legal |
| IIV | Industrial Incr., Voluntary | Incremental |
| IO | Industry Outstanding | Backlog |
| IR | Industry Royalties | Backlog |
| JOP | Job Opportunity Program | Other |
| LFP | Licensee Funded Program | Other |
| M | Ministry | Operational |
| O | Operational | Operational |
| RBC | Forest Renewal B.C. | FRBC |
| RBL | Forest Renewal B.C. - licensee administered | FRBC |
| RBM | Forest Renewal B.C. - ministry administered | FRBC |
| S | Section 88 | Backlog |
| SBF | BC Timber Sales | Legal |
| SMF | South Moresby Forest Replacement Account | Legal |
| TSC | Tree Seed Centre | Other |
| VCV | Provincial Contingency Vote (Special Use Only) | Other |
| VFH | Forest Health | Other |
| VFP | Current Reforestation | Operational |
| VG | Ministry Outstanding | Backlog |
| VI | Provincial Incremental | Incremental |
| VOB | Ministry Vote, SBEP | Backlog |
| VOI | Industry Outstanding | Backlog |
| VRT | Afforestation | Other |
| XXX | No Funding Source | Other |

